### ISSUE TITLE
Rename the async package.

### ISSUE THREAD

**Issue by sander76** [coreGreenberet/homematicip-rest-api#106] opened 2018-06-10 05:25 UTC
Async becomes a protected keyword when 3.7 is released.

**Comment by coreGreenberet** [comment] 2018-06-10 05:53
But how should the package be named? async_?

**Comment by sander76** [comment] 2018-06-10 05:57
@coreGreenberet I was thinking of `aio`.
That is a much used word for packages using asyncio.

**Comment by mxworm** [comment] 2018-06-10 06:00
@sander76 

```
homeassistant/components/homematicip_cloud/config_flow.py", line 27
    from homematicip.async.auth import AsyncAuth
                         ^
SyntaxError: invalid syntax
```

I copied to `asyncc` : -) and the issue is gone.

**Comment by sander76** [comment] 2018-06-10 06:02
@mxworm @coreGreenberet Then it seems the `async` keyword already makes things break. I thought we had some time till 3.7 was released..

**Comment by mxworm** [comment] 2018-06-10 07:09
If you import at the beginning of the file yes, but inside a function not :-)

Vote: aio

**Comment by coreGreenberet** [comment] 2018-06-10 10:03
Let's settle it with aio.
Should we rename the classes to? E.g AsyncHome to AIOHome?

**Comment by mxworm** [comment] 2018-06-10 10:14
I would keep them.

**Comment by sander76** [comment] 2018-06-10 10:48
@coreGreenberet @mxworm Lets keep the class names intact.
Only rename the package.

**Comment by coreGreenberet** [comment] 2018-06-11 11:42
@mxworm @sander76 
I've merged the PR #107 and modified the missing settings.
could you please verify that everything is working on your end with the current head?

If yes I will tag it to create a new release

**Comment by mxworm** [comment] 2018-06-11 19:57
Works perfekt! Thanks!

**Comment by coreGreenberet** [comment] 2018-06-12 07:22
thanks =)
I've also tagged a new version

**Closed by coreGreenberet** 2018-06-12 07:22 UTC
